import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { BotmakerChat } from "../components/BotmakerChat";
import { GlobalToastProvider } from "../components/ui/global-toast";
import { ScrollToTop } from "../components/ScrollToTop";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SocioSA - Portal de Clientes",
  description: "Generated by create next app",
  icons: {
    icon: "/socio.ico",
    shortcut: "/socio.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ScrollToTop />
        <GlobalToastProvider>{children}</GlobalToastProvider>
        <BotmakerChat />
      </body>
    </html>
  );
}
