import type { Metadata } from "next";
import { PortalExpedientesProvider } from "@/lib/portal-expedientes-context";
import { PortalPerfilProvider } from "@/lib/portal-perfil-context";

export const metadata: Metadata = {
  title: "CORA",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PortalPerfilProvider>
      <PortalExpedientesProvider>{children}</PortalExpedientesProvider>
    </PortalPerfilProvider>
  );
}
